$ErrorActionPreference = "Stop"

Install-Package -Id "AngleSharp" -Version 0.9.9 -IgnoreDependencies
Install-Package -Id "AWSSDK.Core" -Version 3.3.5 -IgnoreDependencies
Install-Package -Id "AWSSDK.S3" -Version 3.3.1.2 -IgnoreDependencies
Install-Package -Id "Microsoft.NETCore.Platforms" -Version 1.0.1 -IgnoreDependencies
Install-Package -Id "Libuv" -Version 1.9.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Cryptography.Internal" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.DataProtection.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Resources.ResourceManager" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Runtime" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Primitives" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Http.Features" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Linq" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Configuration.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Hosting.Server.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Text.Encodings.Web" -Version 4.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Http.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.ComponentModel" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Diagnostics.Debug" -Version 4.0.11 -IgnoreDependencies
Install-Package -Id "System.Globalization" -Version 4.0.11 -IgnoreDependencies
Install-Package -Id "System.Linq.Expressions" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "System.Reflection" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.DependencyInjection.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.IO" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.FileProviders.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Collections" -Version 4.0.11 -IgnoreDependencies
Install-Package -Id "System.Collections.Concurrent" -Version 4.0.12 -IgnoreDependencies
Install-Package -Id "System.Runtime.Extensions" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "System.Runtime.InteropServices" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Logging.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Hosting.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Threading" -Version 4.0.11 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Options" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.DataProtection" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Buffers" -Version 4.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.WebUtilities" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.ObjectPool" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Antiforgery" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Authorization" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Diagnostics.Contracts" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Text.Encoding" -Version 4.0.11 -IgnoreDependencies
Install-Package -Id "Microsoft.Net.Http.Headers" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Http.Extensions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Cors" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Diagnostics.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.FileSystemGlobbing" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.FileProviders.Physical" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Diagnostics.DiagnosticSource" -Version 4.0.0 -IgnoreDependencies
Install-Package -Id "System.Collections.Immutable" -Version 1.3.0 -IgnoreDependencies
Install-Package -Id "System.Reflection.Metadata" -Version 1.3.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Diagnostics" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Http" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Configuration" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Configuration.EnvironmentVariables" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Threading.Tasks" -Version 4.0.11 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.DependencyInjection" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Logging" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.PlatformAbstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Runtime.InteropServices.RuntimeInformation" -Version 4.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Hosting" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Html.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.CSharp" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "Newtonsoft.Json" -Version 9.0.1 -IgnoreDependencies
Install-Package -Id "System.ComponentModel.Primitives" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "System.ComponentModel.TypeConverter" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "System.Reflection.Extensions" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Runtime.Serialization.Primitives" -Version 4.1.1 -IgnoreDependencies
Install-Package -Id "System.Text.Encoding.Extensions" -Version 4.0.11 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.JsonPatch" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Globalization.CultureInfoCache" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Localization.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Localization" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Routing.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Routing" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.DotNet.InternalAbstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.DependencyModel" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.Core" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.ApiExplorer" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.Cors" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Localization" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.DataAnnotations" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.Formatters.Json" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Razor" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Razor.Runtime" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Caching.Abstractions" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Caching.Memory" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.Razor.Host" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.WebEncoders" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.ViewFeatures" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.CodeAnalysis.Analyzers" -Version 1.1.0 -IgnoreDependencies
Install-Package -Id "System.AppContext" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "System.Console" -Version 4.0.0 -IgnoreDependencies
Install-Package -Id "System.Diagnostics.FileVersionInfo" -Version 4.0.0 -IgnoreDependencies
Install-Package -Id "System.Diagnostics.StackTrace" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Diagnostics.Tools" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Dynamic.Runtime" -Version 4.0.11 -IgnoreDependencies
Install-Package -Id "System.IO.FileSystem.Primitives" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.IO.FileSystem" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Reflection.Primitives" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Runtime.Handles" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Runtime.Numerics" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Security.Cryptography.Primitives" -Version 4.0.0 -IgnoreDependencies
Install-Package -Id "System.Security.Cryptography.Algorithms" -Version 4.2.0 -IgnoreDependencies
Install-Package -Id "System.Security.Cryptography.Encoding" -Version 4.0.0 -IgnoreDependencies
Install-Package -Id "System.Security.Cryptography.X509Certificates" -Version 4.1.0 -IgnoreDependencies
Install-Package -Id "System.Text.Encoding.CodePages" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Threading.Tasks.Parallel" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Threading.Thread" -Version 4.0.0 -IgnoreDependencies
Install-Package -Id "System.Xml.ReaderWriter" -Version 4.0.11 -IgnoreDependencies
Install-Package -Id "System.Xml.XDocument" -Version 4.0.11 -IgnoreDependencies
Install-Package -Id "System.Xml.XPath" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Xml.XPath.XDocument" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "System.Xml.XmlDocument" -Version 4.0.1 -IgnoreDependencies
Install-Package -Id "Microsoft.CodeAnalysis.Common" -Version 1.3.0 -IgnoreDependencies
Install-Package -Id "Microsoft.CodeAnalysis.CSharp" -Version 1.3.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.FileProviders.Composite" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.Razor" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.Localization" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc.TagHelpers" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Mvc" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "System.Numerics.Vectors" -Version 4.1.1 -IgnoreDependencies
Install-Package -Id "System.Threading.Tasks.Extensions" -Version 4.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.Server.Kestrel" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.AspNetCore.StaticFiles" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Configuration.CommandLine" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Microsoft.Extensions.Logging.Console" -Version 1.0.0 -IgnoreDependencies
Install-Package -Id "Polly" -Version 4.3.0 -IgnoreDependencies
Install-Package -Id "Serilog" -Version 2.3.0 -IgnoreDependencies
Install-Package -Id "Serilog.Extensions.Logging" -Version 1.3.1 -IgnoreDependencies
Install-Package -Id "Serilog.Sinks.Literate" -Version 2.0.0 -IgnoreDependencies